name 'elk-repo'
maintainer 'Samson S. Kolge'
maintainer_email 'eglok1980@gmail.com'
license 'all_rights'
description 'Installs/Configures elk-repo'
long_description 'Installs/Configures elk-repo'
version '0.1.0'
depends 'apt'
