name 'elk-repo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures elk-repo'
long_description 'Installs/Configures elk-repo'
version '0.1.0'
